use e_commerce;

-- ==========================================================
-- 02_Intermediate_SQL.sql
-- AI-Assisted E-commerce Sales & Customer Analytics
-- Intermediate SQL Queries
-- ==========================================================


-- ==========================================================
-- Query 1: Total Orders by Customer State
-- Purpose:
-- Count the total number of orders placed from each state.
-- ==========================================================

SELECT
    c.customer_state,
    COUNT(o.order_id) AS total_orders

FROM olist_customers_dataset c

INNER JOIN olist_orders_dataset o
ON c.customer_id = o.customer_id

GROUP BY c.customer_state

ORDER BY total_orders DESC;


-- ==========================================================
-- Query 2: Total Revenue by Payment Type
-- Purpose:
-- Calculate total revenue generated by each payment method.
-- ==========================================================

SELECT

    payment_type,

    ROUND(SUM(payment_value),2) AS total_revenue

FROM olist_order_payments_dataset

GROUP BY payment_type

ORDER BY total_revenue DESC;


-- ==========================================================
-- Query 3: Top 10 Customer Cities by Orders
-- Purpose:
-- Identify cities with the highest number of orders.
-- ==========================================================

SELECT

    c.customer_city,

    COUNT(o.order_id) AS total_orders

FROM olist_customers_dataset c

INNER JOIN olist_orders_dataset o
ON c.customer_id = o.customer_id

GROUP BY c.customer_city

ORDER BY total_orders DESC

LIMIT 10;


-- ==========================================================
-- Query 4: Average Payment by Payment Type
-- Purpose:
-- Calculate average payment value for each payment method.
-- ==========================================================

SELECT

    payment_type,

    ROUND(AVG(payment_value),2) AS average_payment

FROM olist_order_payments_dataset

GROUP BY payment_type

ORDER BY average_payment DESC;


-- ==========================================================
-- Query 5: Product Categories with More Than 100 Products
-- Purpose:
-- Display categories having more than 100 products.
-- ==========================================================

SELECT

    product_category_name,

    COUNT(product_id) AS total_products

FROM olist_products_dataset

GROUP BY product_category_name

HAVING COUNT(product_id) > 100

ORDER BY total_products DESC;


-- ==========================================================
-- Query 6: Revenue Generated by Each Order
-- Purpose:
-- Calculate total payment received for every order.
-- ==========================================================

SELECT

    order_id,

    ROUND(SUM(payment_value),2) AS total_revenue

FROM olist_order_payments_dataset

GROUP BY order_id

ORDER BY total_revenue DESC;


-- ==========================================================
-- Query 7: Customer Order Status
-- Purpose:
-- Display customer city along with order status.
-- ==========================================================

SELECT

    c.customer_city,

    o.order_id,

    o.order_status

FROM olist_customers_dataset c

INNER JOIN olist_orders_dataset o
ON c.customer_id = o.customer_id

ORDER BY c.customer_city;


-- ==========================================================
-- Query 8: Categorize Orders Based on Payment Value
-- Purpose:
-- Classify orders into Low, Medium and High value.
-- ==========================================================

SELECT

    order_id,

    payment_value,

    CASE

        WHEN payment_value < 100 THEN 'Low Value'

        WHEN payment_value BETWEEN 100 AND 500 THEN 'Medium Value'

        ELSE 'High Value'

    END AS Order_Category

FROM olist_order_payments_dataset

ORDER BY payment_value DESC;


-- ==========================================================
-- Query 9: Top 10 Customers by Total Spending
-- Purpose:
-- Identify customers who spent the most.
-- ==========================================================

SELECT

    c.customer_unique_id,

    ROUND(SUM(p.payment_value),2) AS total_spent

FROM olist_customers_dataset c

INNER JOIN olist_orders_dataset o
ON c.customer_id = o.customer_id

INNER JOIN olist_order_payments_dataset p
ON o.order_id = p.order_id

GROUP BY c.customer_unique_id

ORDER BY total_spent DESC

LIMIT 10;


-- ==========================================================
-- Query 10: Average Product Price by Category
-- Purpose:
-- Calculate the average selling price for each product category.
-- ==========================================================

SELECT

    pr.product_category_name,

    ROUND(AVG(oi.price),2) AS average_price

FROM olist_products_dataset pr

INNER JOIN olist_order_items_dataset oi
ON pr.product_id = oi.product_id

GROUP BY pr.product_category_name

ORDER BY average_price DESC;